/*
//Copyright (c) 2015 Hitachi Data Systems, Inc.
//All Rights Reserved.
//
//   Licensed under the Apache License, Version 2.0 (the "License"); you may
//   not use this file except in compliance with the License. You may obtain
//   a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
//   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
//   License for the specific language governing permissions and limitations
//   under the License.
//
//Package: COMET::Data Ingestor Service
//Author: Cliff Grimm <cliff.grimm@hds.com>
//Compilation Date: 2015-05-06
//License: Apache License, Version 2.0
//Version: 1.21.0
//(RPM) Release: 1
//SVN: r554
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ingestor_metadata_JNIWrapper */

#ifndef _Included_ingestor_metadata_JNIWrapper
#define _Included_ingestor_metadata_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ingestor_metadata_JNIWrapper
 * Method:    getCustomMetadata
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ingestor_metadata_JNIWrapper_getCustomMetadata
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ingestor_metadata_JNIWrapper
 * Method:    initialize
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ingestor_metadata_JNIWrapper_initialize
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
